export const countries = [
    { "country": "United Arab Emirates", "dial_code": "+971", "code": "AE" },
    { "country": "Afghanistan", "dial_code": "+93", "code": "AF" },
    { "country": "Albania", "dial_code": "+355", "code": "AL" },
    { "country": "Algeria", "dial_code": "+213", "code": "DZ" },
    { "country": "Andorra", "dial_code": "+376", "code": "AD" },
    { "country": "Angola", "dial_code": "+244", "code": "AO" },
    { "country": "Argentina", "dial_code": "+54", "code": "AR" },
    { "country": "Armenia", "dial_code": "+374", "code": "AM" },
    { "country": "Australia", "dial_code": "+61", "code": "AU" },
    { "country": "Austria", "dial_code": "+43", "code": "AT" },
    { "country": "Azerbaijan", "dial_code": "+994", "code": "AZ" },
    { "country": "Bahamas", "dial_code": "+1-242", "code": "BS" },
    { "country": "Bahrain", "dial_code": "+973", "code": "BH" },
    { "country": "Bangladesh", "dial_code": "+880", "code": "BD" },
    { "country": "Belarus", "dial_code": "+375", "code": "BY" },
    { "country": "Belgium", "dial_code": "+32", "code": "BE" },
    { "country": "Belize", "dial_code": "+501", "code": "BZ" },
    { "country": "Benin", "dial_code": "+229", "code": "BJ" },
    { "country": "Bhutan", "dial_code": "+975", "code": "BT" },
    { "country": "Bolivia", "dial_code": "+591", "code": "BO" },
    { "country": "Bosnia & Herzegovina", "dial_code": "+387", "code": "BA" },
    { "country": "Botswana", "dial_code": "+267", "code": "BW" },
    { "country": "Brazil", "dial_code": "+55", "code": "BR" },
    { "country": "Brunei", "dial_code": "+673", "code": "BN" },
    { "country": "Bulgaria", "dial_code": "+359", "code": "BG" },
    { "country": "Burkina Faso", "dial_code": "+226", "code": "BF" },
    { "country": "Burundi", "dial_code": "+257", "code": "BI" },
    { "country": "Cambodia", "dial_code": "+855", "code": "KH" },
    { "country": "Cameroon", "dial_code": "+237", "code": "CM" },
    { "country": "Canada", "dial_code": "+1", "code": "CA" },
    { "country": "Cape Verde", "dial_code": "+238", "code": "CV" },
    { "country": "Central African Republic", "dial_code": "+236", "code": "CF" },
    { "country": "Chad", "dial_code": "+235", "code": "TD" },
    { "country": "Chile", "dial_code": "+56", "code": "CL" },
    { "country": "China", "dial_code": "+86", "code": "CN" },
    { "country": "Colombia", "dial_code": "+57", "code": "CO" },
    { "country": "Comoros", "dial_code": "+269", "code": "KM" },
    { "country": "Costa Rica", "dial_code": "+506", "code": "CR" },
    { "country": "Croatia", "dial_code": "+385", "code": "HR" },
    { "country": "Cuba", "dial_code": "+53", "code": "CU" },
    { "country": "Cyprus", "dial_code": "+357", "code": "CY" },
    { "country": "Czech Republic", "dial_code": "+420", "code": "CZ" },
    { "country": "Democratic Republic of the Congo", "dial_code": "+243", "code": "CD" },
    { "country": "Denmark", "dial_code": "+45", "code": "DK" },
    { "country": "Djibouti", "dial_code": "+253", "code": "DJ" },
    { "country": "Dominica", "dial_code": "+1-767", "code": "DM" },
    { "country": "Dominican Republic", "dial_code": "+1-809", "code": "DO" },
    { "country": "Ecuador", "dial_code": "+593", "code": "EC" },
    { "country": "Egypt", "dial_code": "+20", "code": "EG" },
    { "country": "El Salvador", "dial_code": "+503", "code": "SV" },
    { "country": "Equatorial Guinea", "dial_code": "+240", "code": "GQ" },
    { "country": "Eritrea", "dial_code": "+291", "code": "ER" },
    { "country": "Estonia", "dial_code": "+372", "code": "EE" },
    { "country": "Eswatini", "dial_code": "+268", "code": "SZ" },
    { "country": "Ethiopia", "dial_code": "+251", "code": "ET" },
    { "country": "Fiji", "dial_code": "+679", "code": "FJ" },
    { "country": "Finland", "dial_code": "+358", "code": "FI" },
    { "country": "France", "dial_code": "+33", "code": "FR" },
    { "country": "Gabon", "dial_code": "+241", "code": "GA" },
    { "country": "Georgia", "dial_code": "+995", "code": "GE" },
    { "country": "Germany", "dial_code": "+49", "code": "DE" },
    { "country": "Ghana", "dial_code": "+233", "code": "GH" },
    { "country": "Greece", "dial_code": "+30", "code": "GR" },
    { "country": "Guatemala", "dial_code": "+502", "code": "GT" },
    { "country": "Guinea", "dial_code": "+224", "code": "GN" },
    { "country": "Guinea-Bissau", "dial_code": "+245", "code": "GW" },
    { "country": "Guyana", "dial_code": "+592", "code": "GY" },
    { "country": "Haiti", "dial_code": "+509", "code": "HT" },
    { "country": "Honduras", "dial_code": "+504", "code": "HN" },
    { "country": "Hong Kong", "dial_code": "+852", "code": "HK" },
    { "country": "Hungary", "dial_code": "+36", "code": "HU" },
    { "country": "Iceland", "dial_code": "+354", "code": "IS" },
    { "country": "India", "dial_code": "+91", "code": "IN" },
    { "country": "Indonesia", "dial_code": "+62", "code": "ID" },
    { "country": "Iraq", "dial_code": "+964", "code": "IQ" },
    { "country": "Ireland", "dial_code": "+353", "code": "IE" },
    { "country": "Israel", "dial_code": "+972", "code": "IL" },
    { "country": "Italy", "dial_code": "+39", "code": "IT" },
    { "country": "Jamaica", "dial_code": "+1-876", "code": "JM" },
    { "country": "Japan", "dial_code": "+81", "code": "JP" },
    { "country": "Jordan", "dial_code": "+962", "code": "JO" },
    { "country": "Kazakhstan", "dial_code": "+7", "code": "KZ" },
    { "country": "Kenya", "dial_code": "+254", "code": "KE" },
    { "country": "Kosovo", "dial_code": "+383", "code": "XK" },
    { "country": "Kuwait", "dial_code": "+965", "code": "KW" },
    { "country": "Kyrgyzstan", "dial_code": "+996", "code": "KG" },
    { "country": "Laos", "dial_code": "+856", "code": "LA" },
    { "country": "Latvia", "dial_code": "+371", "code": "LV" },
    { "country": "Lebanon", "dial_code": "+961", "code": "LB" },
    { "country": "Lesotho", "dial_code": "+266", "code": "LS" },
    { "country": "Liberia", "dial_code": "+231", "code": "LR" },
    { "country": "Libya", "dial_code": "+218", "code": "LY" },
    { "country": "Liechtenstein", "dial_code": "+423", "code": "LI" },
    { "country": "Lithuania", "dial_code": "+370", "code": "LT" },
    { "country": "Luxembourg", "dial_code": "+352", "code": "LU" },
    { "country": "Macau", "dial_code": "+853", "code": "MO" },
    { "country": "Madagascar", "dial_code": "+261", "code": "MG" },
    { "country": "Malawi", "dial_code": "+265", "code": "MW" },
    { "country": "Malaysia", "dial_code": "+60", "code": "MY" },
    { "country": "Maldives", "dial_code": "+960", "code": "MV" },
    { "country": "Mali", "dial_code": "+223", "code": "ML" },
    { "country": "Malta", "dial_code": "+356", "code": "MT" },
    { "country": "Mauritania", "dial_code": "+222", "code": "MR" },
    { "country": "Mauritius", "dial_code": "+230", "code": "MU" },
    { "country": "Mexico", "dial_code": "+52", "code": "MX" },
    { "country": "Moldova", "dial_code": "+373", "code": "MD" },
    { "country": "Monaco", "dial_code": "+377", "code": "MC" },
    { "country": "Mongolia", "dial_code": "+976", "code": "MN" },
    { "country": "Montenegro", "dial_code": "+382", "code": "ME" },
    { "country": "Morocco", "dial_code": "+212", "code": "MA" },
    { "country": "Myanmar (Burma)", "dial_code": "+95", "code": "MM" },
    { "country": "Namibia", "dial_code": "+264", "code": "NA" },
    { "country": "Nepal", "dial_code": "+977", "code": "NP" },
    { "country": "Netherlands", "dial_code": "+31", "code": "NL" },
    { "country": "New Zealand", "dial_code": "+64", "code": "NZ" },
    { "country": "Nicaragua", "dial_code": "+505", "code": "NI" },
    { "country": "Niger", "dial_code": "+227", "code": "NE" },
    { "country": "Nigeria", "dial_code": "+234", "code": "NG" },
    { "country": "North Korea", "dial_code": "+850", "code": "KP" },
    { "country": "North Macedonia", "dial_code": "+389", "code": "MK" },
    { "country": "Norway", "dial_code": "+47", "code": "NO" },
    { "country": "Oman", "dial_code": "+968", "code": "OM" },
    { "country": "Pakistan", "dial_code": "+92", "code": "PK" },
    { "country": "Palestine", "dial_code": "+970", "code": "PS" },
    { "country": "Panama", "dial_code": "+507", "code": "PA" },
    { "country": "Papua New Guinea", "dial_code": "+675", "code": "PG" },
    { "country": "Paraguay", "dial_code": "+595", "code": "PY" },
    { "country": "Peru", "dial_code": "+51", "code": "PE" },
    { "country": "Philippines", "dial_code": "+63", "code": "PH" },
    { "country": "Poland", "dial_code": "+48", "code": "PL" },
    { "country": "Portugal", "dial_code": "+351", "code": "PT" },
    { "country": "Puerto Rico", "dial_code": "+1-787", "code": "PR" },
    { "country": "Qatar", "dial_code": "+974", "code": "QA" },
    { "country": "Republic of the Congo", "dial_code": "+242", "code": "CG" },
    { "country": "Romania", "dial_code": "+40", "code": "RO" },
    { "country": "Russia", "dial_code": "+7", "code": "RU" },
    { "country": "Rwanda", "dial_code": "+250", "code": "RW" },
    { "country": "Saint Kitts & Nevis", "dial_code": "+1-869", "code": "KN" },
    { "country": "Saint Lucia", "dial_code": "+1-758", "code": "LC" },
    { "country": "Saint Vincent & the Grenadines", "dial_code": "+1-784", "code": "VC" },
    { "country": "Samoa", "dial_code": "+685", "code": "WS" },
    { "country": "San Marino", "dial_code": "+378", "code": "SM" },
    { "country": "São Tomé & Príncipe", "dial_code": "+239", "code": "ST" },
    { "country": "Saudi Arabia", "dial_code": "+966", "code": "SA" },
    { "country": "Senegal", "dial_code": "+221", "code": "SN" },
    { "country": "Serbia", "dial_code": "+381", "code": "RS" },
    { "country": "Seychelles", "dial_code": "+248", "code": "SC" },
    { "country": "Sierra Leone", "dial_code": "+232", "code": "SL" },
    { "country": "Singapore", "dial_code": "+65", "code": "SG" },
    { "country": "Slovakia", "dial_code": "+421", "code": "SK" },
    { "country": "Slovenia", "dial_code": "+386", "code": "SI" },
    { "country": "Solomon Islands", "dial_code": "+677", "code": "SB" },
    { "country": "Somalia", "dial_code": "+252", "code": "SO" },
    { "country": "South Africa", "dial_code": "+27", "code": "ZA" },
    { "country": "South Korea", "dial_code": "+82", "code": "KR" },
    { "country": "South Sudan", "dial_code": "+211", "code": "SS" },
    { "country": "Spain", "dial_code": "+34", "code": "ES" },
    { "country": "Sri Lanka", "dial_code": "+94", "code": "LK" },
    { "country": "Sudan", "dial_code": "+249", "code": "SD" },
    { "country": "Suriname", "dial_code": "+597", "code": "SR" },
    { "country": "Sweden", "dial_code": "+46", "code": "SE"},
    { "country": "Switzerland", "dial_code": "+41", "code": "CH" },
    { "country": "Syria", "dial_code": "+963", "code": "SY" },
    { "country": "Taiwan", "dial_code": "+886", "code": "TW" },
    { "country": "Tajikistan", "dial_code": "+992", "code": "TJ" },
    { "country": "Tanzania", "dial_code": "+255", "code": "TZ" },
    { "country": "Thailand", "dial_code": "+66", "code": "TH" },
    { "country": "Togo", "dial_code": "+228", "code": "TG" },
    { "country": "Tonga", "dial_code": "+676", "code": "TO" },
    { "country": "Tunisia", "dial_code": "+216", "code": "TN" },
    { "country": "Turkey", "dial_code": "+90", "code": "TR" },
    { "country": "Turkmenistan", "dial_code": "+993", "code": "TM" },
    { "country": "Uganda", "dial_code": "+256", "code": "UG" },
    { "country": "Ukraine", "dial_code": "+380", "code": "UA" },
    { "country": "United Arab Emirates", "dial_code": "+971", "code": "AE" },
    { "country": "United Kingdom", "dial_code": "+44", "code": "GB" },
    { "country": "United States", "dial_code": "+1", "code": "US" },
    { "country": "Uruguay", "dial_code": "+598", "code": "UY" },
    { "country": "Uzbekistan", "dial_code": "+998", "code": "UZ" },
    { "country": "Vanuatu", "dial_code": "+678", "code": "VU" },
    { "country": "Vatican City", "dial_code": "+379", "code": "VA" },
    { "country": "Venezuela", "dial_code": "+58", "code": "VE" },
    { "country": "Vietnam", "dial_code": "+84", "code": "VN" },
    { "country": "Yemen", "dial_code": "+967", "code": "YE" },
    { "country": "Zambia", "dial_code": "+260", "code": "ZM" },
    { "country": "Zimbabwe", "dial_code": "+263", "code": "ZW" }
  ]