export const resources = {
    en: {
      translation: {
        hello: 'Hello',
        welcome: 'Welcome, {{name}}!',
        guest: 'Hello guest!',
        cart_items: '{{count}} item',
        cart_items_plural: '{{count}} items',
        orders: 'Orders',
        home: 'Home',
        wishlist: 'WishList',
        categories: 'Categories',
        cart: 'My Cart',
        account: 'Account',
        auth: 'LOGIN OR REGISTER',
        profile: 'Profile',
        trackOrders: 'Track your orders',
        profileManage: 'Manage Profile',
        returns: 'Returns',
        activeReturns: '{{count}} Active requests',
        trackYourReturns: 'Track your returns',
        wishListCount: '{{count}} Wish Products',
        myAddresses: 'My Addresses',
        myCart: 'My Cart',
        paymentMethod: 'Payment Method',
        recentlyViewed: 'Recently Viewed',
        secure: 'Security',
        langs: 'Languages',
        notifications: 'Notifications',
        country: 'Country',
        signout: 'Sign Out',
        myAccount: 'My Account',
        pinfo: 'Profile Information',
        email: 'Email',
        firstName: 'First Name',
        lastName: 'Last Name',
        phone: 'Phone number',
        app: 'Zuvo',
        cancel: 'Cancel',
        close: 'Close',
        addNewAddress: 'Add New Address',
        confirm: 'Confirm',
        edit: 'Edit',
        delete: 'Delete',
        default: 'Default',
        name: 'Name',
        address: 'Address',
        mobile: 'Mobile',
        confirmAddress: 'CONFIRM ADDRESS',
        locationInfo: 'Location Information',
        addAddressDetails: 'Additional Address Details',
        personalInfo: 'Personal Information',
        saveAddress: 'Save Address',
        dropPackage: 'Where do you want us to drop your package?',
        mobileNumber: 'Mobile Number',
        enterPhoneNumber: "Enter Phone Number",
        farAway: 'You seem far away from this location!',
        changeAddress: 'Change address',
        ec: 'Engine Components',
        gbc: 'Gearbox Components',
        brake: 'Brake Pads',
        tires: 'Tires',
        wiper: 'Wiper Blades',
        steering: 'Steering Components',
        cooling: 'Cooling System',
        search: 'Search',
        items: '{{count}} Items',
        inCart: 'IN CART',
        addToCart: 'ADD TO CART',
        off: 'OFF',
        singleCart: 'Cart',
        easyReturn: 'Easy Return',
        hideDetails: 'Hide details',
        getIt: 'Get it',
        tom: 'Tomorrow',
        order: 'Order',
        orderIn: 'Order in',
        checkoutCAP: 'CHECKOUT',
        checkout: 'Checkout',
        viewAll: 'ViEW ALL',
        fromYourWish: 'From your Wishlist',
        apply: 'Apply',
        enterCoupon: 'Enter Coupon Code',
        viewDiscounts: 'View All Discounts',
        subTotal: 'Subtotal',
        shipFee: 'Shipping Fee',
        total: 'Total',
        h: 'h',
        m: 'm',
        year: 'year',
        month: 'month',
        day: 'day',
        warranty: 'warranty',
        freeDel: 'Free Delivery',
        free: 'Free',
        addresses: 'Addresses',
        recommendedForYou: 'Recommended For You',
        recommended: 'Recommended',
        soldOut: 'Sold Out',
        bestSeller: 'Best Seller',
        lowestPriceInMarket: 'Lowest price in market',
        previouslyBrowsed: 'Previously Browsed',
        bestDeals: 'Best Deals',
        whatAreYouLooking: 'What are you looking for?',
        ad: 'Ad',
        incVat: 'Incl. VAT',
        soldRec: 'sold recently',
        getDelTom: 'Get delivery Tomorrow with ZuFast',
        discountWithCoupon : "Extra {{discount}}% off  •  CODE: ZuvoTheOne",
        bestSellerNumber: "Best seller #{{rank}} in Engine Oils",
        delByZuvo: "Delivery by Zuvo",
        cashOnDel: "Cash on Delivery",
        lowReturns: "Low Returns",
        secureTrans: "Secure Transaction",
        previouslyBrowsedProd: 'Previously Browsed Products',
        bestSellerInCat: 'Best Seller in this category',
        frequently: 'Frequently Bought Together',
        buyTogether: 'Buy them together',
        soldBy: 'Sold by',
        partnerSince: "Partner since",
        overview: 'Overview',
        specifications: 'Specifications',
        backToTop: 'Back To Top',
        qty: 'QTY',
        reviewRating: 'Ratings & reviews',
        basedOn: 'Based on {{count}} rating',
        productNoReview: 'This product does not have any reviews yet.',
        customerAlsoReviewed: 'Customer Also Viewed',
        productsRelated: 'Products related to this',
        weight: 'Weight (KG)',
        fuelType: 'Fuel Type',
        material: 'Material',
        dimensions: 'Dimensions',
        colorFinish: 'Color Finish',
        certifications: 'Certifications',
        voltageAmperage: 'Voltage amperage',
        performanceNotes: 'Performance Notes',
        transmissionType: 'Transmission Type',
        oemNumber: 'OEM Number',
        contshop: 'Continue Shopping',
        checkOut: 'Checkout',
        deliveryAddress: 'Delivery Address',
        deliveryInstructions: 'Delivery Instructions',
        leaveAtMyDoor: 'Leave at my door',
        whoWillReceive: 'Who will receive this order?',
        someoneElse: 'Someone else',
        shipment: 'Shipment',
        freeDeliveryTop: '',
        getItToday: 'Get it today',
        getItTomorrow: 'Get it tomorrow',
        payWith: 'Pay With',
        orderSummary: 'Order Summary',
        itemsCount: '{{ count }} Items',
        extraCharges: "Extra charges may be applied",
        cod: 'Cash On Delivery',
        slideToOrder: 'Slide To Order'
      },
    },
    ar: {
      translation: {
        hello: 'مرحبا',
        welcome: 'أهلاً، {{name}}!',
        guest: 'مرحبا ضيف!',
        cart_items: '{{count}} عنصر',
        cart_items_plural: '{{count}} عناصر',
        orders: 'الطلبات',
        home: 'الرئيسيه',
        wishlist: 'المفضله',
        categories: 'الاقسام',
        cart: 'السله',
        account: 'حسابي',
        auth: 'تسجيل دخول',
        profile: 'صفحتي',
        trackOrders: 'تتبع طلباتك',
         profileManage: 'تحكم بصفحتك',
        returns: 'المرتجعات',
        activeReturns: '{{count}} طلب مرتجع نشط',
        wishListCount: '{{count}} منتج مفضل',
        myAddresses: 'العناوين',
        myCart: 'سله المشتريات',
        paymentMethod: 'طرق الدفع',
        recentlyViewed: 'تم مشاهدتها مؤخرآ',
        secure: 'الامان',
        langs: 'اللغه',
        notifications: 'الاشعارات',
        country: 'البلد',
        signout: 'تسجيل خروج',
        myAccount: 'حسابي',
        pinfo: 'البيانات الشخصيه',
        email: 'البريد الالكتروني',
        firstName: 'الاسم الاول',
        lastName: 'الاسم الاخير',
        phone: 'رقم الهاتف',
        app: 'زوفو',
        cancel: 'اٍلغاء',
        close: 'اِغلاق',
        addNewAddress: 'اْضافه عنوان جديد',
        confirm: 'تاٌكيد',
        edit: 'تعديل',
        delete: 'مسح',
        default: 'الافتراضي',
        name: 'الاسم',
        address: 'العنوان',
        mobile: 'الهاتف',
        confirmAddress: 'تاْكيد العنوان',
        locationInfo: 'معلومات العنوان',
        addAddressDetails: 'معلومات اضافيه للعنوان',
        personalInfo: 'معلومات شخصيه',
        saveAddress: 'حفظ العنوان',
        dropPackage: 'اين تريد توصيل طلبك؟',
        mobileNumber: 'رقم الهاتف',
        enterPhoneNumber: "ادخل رقم الهاتف",
        farAway: 'يبدو انك بعيد عن هذا العنوان',
        changeAddress: 'تغيير العنوان ',
        ec: 'مكونات المحرك',
        gbc: 'مكونات ناقل الحركه',
        brake: 'منصات الفرامل',
        tires: 'الإطارات',
        wiper: 'شفرات المساحات',
        steering: 'مكونات التوجيه',
        cooling: 'نظام التبريد',
        search: 'بحث ',
        items: '{{count}} منتج',
        inCart: 'في السله',
        addToCart: 'اضف الي السله',
        off: 'خصم',
        singleCart: 'السله',
        easyReturn: 'سهوله استرجاع',
        hideDetails: 'اخفاء التفاصيل',
        getIt: 'اْحصل عليها',
        tom: 'غدآ',
        order: 'اطلب',
        orderIn: 'اطلب خلال',
        checkoutCAP: 'اٍتمام الشراء',
        checkout: 'اٍتمام عمليه الشراء',
        viewAll: 'عرض الكل',
        fromYourWish: 'منتجات المفضله',
        apply: 'تطبيق',
        enterCoupon: 'ادخل كود الكوبون',
        viewDiscounts: 'عرض كل الخصومات',
        subTotal: 'المجموع الفرعي',
        shipFee: 'رسوم الشحن',
        total: 'المجموع',
        h: 'س',
        m: 'د',
        year: 'سنه',
        month: 'شهر',
        day: 'يوم',
        warranty: 'ضمان',
        freeDel: 'توصيل مجاني',
        free: 'مجاني',
        addresses: 'العناوين',
        recommendedForYou: 'منتجات يوصي بها',
        recommended: 'يوصي بها',
        soldOut: 'غير متاح',
        bestSeller: 'الافضل مبيعآ',
        lowestPriceInMarket: 'ارخص سعر في السوق',
        previouslyBrowsed: 'منتجات شاهدتها من قبل',
        bestDeals: 'افضل عروض',
        whatAreYouLooking: 'ما الذي تبحث عنه؟',
        ad: 'اِِعلان',
        incVat: 'الرسوم مضافه',
        soldRec: 'مباع حاليآ',
        getDelTom: 'توصيل غدآ من خلال زوفو السريع!',
        discountWithCoupon: '{{discount}}%  خصم اضافي عند استخدام كود ZuvuTheOne',
        bestSellerNumber: 'الافضل مبيعآ رقم في قسم {{category}} {{rank}}',
        delByZuvo: "التوصيل عن طريق زوفو",
        cashOnDel: "الدفع عند الاستلام",
        lowReturns: "نادر الاسترجاع",
        secureTrans: "عمليات دفع امنه",
        previouslyBrowsedProd: 'منتجات شاهدتها من قبل',
        bestSellerInCat: 'الافضل مبيعا في هذا القسم',
        frequently: 'تم شراهؤها بشكل متكرر',
        buyTogether: 'اشتريهم كلهم سويا',
        soldBy: 'مباع من خلال',
        partnerSince: 'شريك من',
        overview: 'الملخص',
        specifications: 'المواصفات',
        backToTop: 'الرجوع للاعلي',
        qty: 'العدد',
        reviewRating: 'التقييمات و المراجعات',
        basedOn: 'بناء علي {{ count }} تقييم ',
        productNoReview: 'لا يوجد اي مراجعه لهذا المنتج',
        customerAlsoReviewed: 'شاهد العملاء ايضآ',
        productsRelated: 'منتجات متعلقه بهذا',
        weight: 'الوزع (كيلو جرام)',
        fuelType: 'نوع الوقود',
        material: 'الخامه',
        dimensions: 'الابعاد',
        colorFinish: 'اللون',
        certifications: 'الشهادات',
        voltageAmperage: 'الفولت و الامبير',
        performanceNotes: 'ملاخظات القدره',
        transmissionType: 'نوع الناقل',
        oemNumber: 'الكود المرجعي',
        contshop: 'تابع الشراء',
        checkOut: "الشراء",
        deliveryAddress: 'عنوان التوصيل',
        deliveryInstructions: 'تعليمات التوصيل',
        leaveAtMyDoor: 'اتركها علي الباب',
        whoWillReceive: 'من الذي يستلم الطلب؟',
        someoneElse: 'شخص اخر',
        shipment: 'الطلب',
        freeDeliveryTop: '',
        getItToday: 'استلمها اليوم',
        getItTomorrow: 'استلمها غدآ',
        payWith: 'ادفع بواسطه',
        orderSummary: 'بيانات الطلب',
        itemsCount: '{{ count }} منتج',
        extraCharges: "سيتم اضافه بعض الرسوم",
        cod: 'الدفع عند الاستلام',
        slideToOrder: 'اتمام الطلب',
        trackYourReturns: 'متابعه المرتجعات'
      },
    },
  } as const;